# ================== Hyprland - TheGirlPuma Edition ==================

# === MONITORE ===
monitor=HDMI-A-1,1920x1080@60,0x0,1      # Dell links
monitor=DP-1,2560x1440@144,1920x0,1      # MSI rechts

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    blur {
        enabled = true
    }
}

# Maus wie Windows
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Fenster
bind = SUPER, Q, killactive
bind = SUPER, M, togglefloating
bind = SUPER, N, movetoworkspacesilent special:minimized
bind = SUPER+Shift, N, togglespecialworkspace minimized

# Menü
bind = SUPER, D, exec, wofi --show drun --normal-window
bind = SUPER, Return, exec, kitty

bind = SUPER+Shift, E, exit

input {
    kb_layout = de
    follow_mouse = 1
}

exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
